training_args:
  per_device_train_batch_size: 8
  per_device_eval_batch_size: 1
  report_to: none
  remove_unused_columns: False
  ddp_find_unused_parameters: False
  output_dir: outputs/test_output
  save_strategy: steps
  save_steps: 500
  save_total_limit: 3
  logging_steps: 10
  eval_strategy: "steps"
  eval_steps: 100
  metric_for_best_model: mse
  greater_is_better: False
  learning_rate: 1e-4
