training_args:
  per_device_train_batch_size: 8
  per_device_eval_batch_size: 8
  report_to: none
  remove_unused_columns: False
  ddp_find_unused_parameters: False
  output_dir: outputs/test_output
  save_strategy: steps
  save_steps: 500
  save_total_limit: 3
  logging_steps: 10
