unet:
  _target_: radar.modeling_diff.unet_conditional.UNet2DConditionModel
  sample_size: [48, 64]
  in_channels: 1
  out_channels: 1
  cross_attention_dim: 256
  block_out_channels: [32, 64, 128, 256]
  r_conditional_encoder_type: "simple_conditional_encoder"
  r_conditional_encoder_kwargs:
    in_channels: 1
    out_channels: 32
    block_out_channels: [64, 128, 256]

scheduler:
  _target_: diffusers.schedulers.scheduling_ddpm.DDPMScheduler
  num_train_timesteps: 1000

pipline:
  _target_: radar.modeling_diff.diff_pipline.RDDPMPipeline
